# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_nibp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNIBP(object):
    def setupUi(self, FormNIBP):
        FormNIBP.setObjectName("FormNIBP")
        FormNIBP.resize(342, 130)
        self.label = QtWidgets.QLabel(FormNIBP)
        self.label.setGeometry(QtCore.QRect(50, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nibpModeComboBox = QtWidgets.QComboBox(FormNIBP)
        self.nibpModeComboBox.setGeometry(QtCore.QRect(160, 10, 131, 31))
        self.nibpModeComboBox.setObjectName("nibpModeComboBox")
        self.nibpModeComboBox.addItem("")
        self.startMeasButton = QtWidgets.QPushButton(FormNIBP)
        self.startMeasButton.setGeometry(QtCore.QRect(40, 80, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.startMeasButton.setFont(font)
        self.startMeasButton.setObjectName("startMeasButton")
        self.stopMeasButton = QtWidgets.QPushButton(FormNIBP)
        self.stopMeasButton.setGeometry(QtCore.QRect(210, 80, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.stopMeasButton.setFont(font)
        self.stopMeasButton.setObjectName("stopMeasButton")

        self.retranslateUi(FormNIBP)
        QtCore.QMetaObject.connectSlotsByName(FormNIBP)

    def retranslateUi(self, FormNIBP):
        _translate = QtCore.QCoreApplication.translate
        FormNIBP.setWindowTitle(_translate("FormNIBP", "血压参数设置"))
        self.label.setText(_translate("FormNIBP", "测量模式："))
        self.nibpModeComboBox.setItemText(0, _translate("FormNIBP", "手动"))
        self.startMeasButton.setText(_translate("FormNIBP", "开始测量"))
        self.stopMeasButton.setText(_translate("FormNIBP", "停止测量"))
