# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1218, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ecg1Label = QtWidgets.QLabel(self.centralwidget)
        self.ecg1Label.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.ecg1Label.setObjectName("ecg1Label")
        self.ecg1WaveLabel = QtWidgets.QLabel(self.centralwidget)
        self.ecg1WaveLabel.setGeometry(QtCore.QRect(10, 50, 941, 131))
        self.ecg1WaveLabel.setObjectName("ecg1WaveLabel")
        self.spo2Label = QtWidgets.QLabel(self.centralwidget)
        self.spo2Label.setGeometry(QtCore.QRect(10, 250, 72, 15))
        self.spo2Label.setObjectName("spo2Label")
        self.spo2WaveLabel = QtWidgets.QLabel(self.centralwidget)
        self.spo2WaveLabel.setGeometry(QtCore.QRect(10, 270, 941, 131))
        self.spo2WaveLabel.setObjectName("spo2WaveLabel")
        self.respLabel = QtWidgets.QLabel(self.centralwidget)
        self.respLabel.setGeometry(QtCore.QRect(10, 490, 72, 15))
        self.respLabel.setObjectName("respLabel")
        self.respWaveLabel = QtWidgets.QLabel(self.centralwidget)
        self.respWaveLabel.setGeometry(QtCore.QRect(10, 510, 941, 131))
        self.respWaveLabel.setObjectName("respWaveLabel")
        self.ecgInfoGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ecgInfoGroupBox.setGeometry(QtCore.QRect(990, 50, 201, 131))
        self.ecgInfoGroupBox.setStyleSheet("        QGroupBox {\n"
"            background-color: #21252B;\n"
"            border: 1px solid #3E4451;\n"
"            border-radius: 6px;\n"
"            margin-top: 0px;\n"
"        }")
        self.ecgInfoGroupBox.setTitle("")
        self.ecgInfoGroupBox.setFlat(False)
        self.ecgInfoGroupBox.setObjectName("ecgInfoGroupBox")
        self.heartRateTextLabel = QtWidgets.QLabel(self.ecgInfoGroupBox)
        self.heartRateTextLabel.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.heartRateTextLabel.setFont(font)
        self.heartRateTextLabel.setObjectName("heartRateTextLabel")
        self.heartRateUnitLabel = QtWidgets.QLabel(self.ecgInfoGroupBox)
        self.heartRateUnitLabel.setGeometry(QtCore.QRect(160, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.heartRateUnitLabel.setFont(font)
        self.heartRateUnitLabel.setObjectName("heartRateUnitLabel")
        self.heartRateLabel = QtWidgets.QLabel(self.ecgInfoGroupBox)
        self.heartRateLabel.setGeometry(QtCore.QRect(90, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.heartRateLabel.setFont(font)
        self.heartRateLabel.setObjectName("heartRateLabel")
        self.heartLabel = QtWidgets.QLabel(self.ecgInfoGroupBox)
        self.heartLabel.setGeometry(QtCore.QRect(10, 60, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.heartLabel.setFont(font)
        self.heartLabel.setStyleSheet("image: url(:/png/image/heart.png);")
        self.heartLabel.setText("")
        self.heartLabel.setPixmap(QtGui.QPixmap(":/new/prefix1/image/heart.png"))
        self.heartLabel.setScaledContents(True)
        self.heartLabel.setObjectName("heartLabel")
        self.labelecg_status = QtWidgets.QLabel(self.ecgInfoGroupBox)
        self.labelecg_status.setGeometry(QtCore.QRect(60, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.labelecg_status.setFont(font)
        self.labelecg_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelecg_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelecg_status.setObjectName("labelecg_status")
        self.spo2InfoGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.spo2InfoGroupBox.setGeometry(QtCore.QRect(990, 270, 201, 131))
        self.spo2InfoGroupBox.setStyleSheet("        QGroupBox {\n"
"            background-color: #21252B;\n"
"            border: 1px solid #3E4451;\n"
"            border-radius: 6px;\n"
"            margin-top: 0px;\n"
"        }")
        self.spo2InfoGroupBox.setTitle("")
        self.spo2InfoGroupBox.setObjectName("spo2InfoGroupBox")
        self.spo2InfoLabel = QtWidgets.QLabel(self.spo2InfoGroupBox)
        self.spo2InfoLabel.setGeometry(QtCore.QRect(80, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.spo2InfoLabel.setFont(font)
        self.spo2InfoLabel.setObjectName("spo2InfoLabel")
        self.labelSPO2Data = QtWidgets.QLabel(self.spo2InfoGroupBox)
        self.labelSPO2Data.setGeometry(QtCore.QRect(70, 50, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.labelSPO2Data.setFont(font)
        self.labelSPO2Data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelSPO2Data.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSPO2Data.setObjectName("labelSPO2Data")
        self.spo2UnitLabel = QtWidgets.QLabel(self.spo2InfoGroupBox)
        self.spo2UnitLabel.setGeometry(QtCore.QRect(110, 50, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.spo2UnitLabel.setFont(font)
        self.spo2UnitLabel.setObjectName("spo2UnitLabel")
        self.labelspo2_status = QtWidgets.QLabel(self.spo2InfoGroupBox)
        self.labelspo2_status.setGeometry(QtCore.QRect(60, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.labelspo2_status.setFont(font)
        self.labelspo2_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelspo2_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelspo2_status.setObjectName("labelspo2_status")
        self.respInfoGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.respInfoGroupBox.setGeometry(QtCore.QRect(990, 510, 201, 131))
        self.respInfoGroupBox.setStyleSheet("        QGroupBox {\n"
"            background-color: #21252B;\n"
"            border: 1px solid #3E4451;\n"
"            border-radius: 6px;\n"
"            margin-top: 0px;\n"
"        }")
        self.respInfoGroupBox.setTitle("")
        self.respInfoGroupBox.setObjectName("respInfoGroupBox")
        self.respUnitLabel = QtWidgets.QLabel(self.respInfoGroupBox)
        self.respUnitLabel.setGeometry(QtCore.QRect(70, 0, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.respUnitLabel.setFont(font)
        self.respUnitLabel.setObjectName("respUnitLabel")
        self.respRateLabel = QtWidgets.QLabel(self.respInfoGroupBox)
        self.respRateLabel.setGeometry(QtCore.QRect(80, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.respRateLabel.setFont(font)
        self.respRateLabel.setObjectName("respRateLabel")
        self.labelresp_status = QtWidgets.QLabel(self.respInfoGroupBox)
        self.labelresp_status.setGeometry(QtCore.QRect(60, 90, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.labelresp_status.setFont(font)
        self.labelresp_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelresp_status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelresp_status.setObjectName("labelresp_status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1218, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_serial = QtWidgets.QAction(MainWindow)
        self.action_serial.setObjectName("action_serial")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ParamMonitor"))
        self.ecg1Label.setText(_translate("MainWindow", "ECG"))
        self.ecg1WaveLabel.setText(_translate("MainWindow", "TextLabel"))
        self.spo2Label.setText(_translate("MainWindow", "SPO2"))
        self.spo2WaveLabel.setText(_translate("MainWindow", "TextLabel"))
        self.respLabel.setText(_translate("MainWindow", "RESP"))
        self.respWaveLabel.setText(_translate("MainWindow", "TextLabel"))
        self.heartRateTextLabel.setText(_translate("MainWindow", "心率"))
        self.heartRateUnitLabel.setText(_translate("MainWindow", "bpm"))
        self.heartRateLabel.setText(_translate("MainWindow", "---"))
        self.labelecg_status.setText(_translate("MainWindow", "心电导联"))
        self.spo2InfoLabel.setText(_translate("MainWindow", "血氧"))
        self.labelSPO2Data.setText(_translate("MainWindow", "---"))
        self.spo2UnitLabel.setText(_translate("MainWindow", "%"))
        self.labelspo2_status.setText(_translate("MainWindow", "血氧导联"))
        self.respUnitLabel.setText(_translate("MainWindow", "呼吸 bpm"))
        self.respRateLabel.setText(_translate("MainWindow", "---"))
        self.labelresp_status.setText(_translate("MainWindow", "呼吸导联"))
        self.action_about.setText(_translate("MainWindow", "关于本软件"))
        self.action_serial.setText(_translate("MainWindow", "串口设置"))
        self.action_quit.setText(_translate("MainWindow", "退出"))
import img_rc
